name: Manage aks-acr infrastructure

on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
          
      - name: Terraform init
        id: init
        run: terraform init -var appId="${{ secrets.TF_SPN_ID }}" -var objectId="${{ secrets.TF_SPN_OBJECT }}" -var secret="${{ secrets.TF_SPN_SECRET }}" -var tenant="${{ secrets.AZURE_TENANT }}" -var subscription="${{ secrets.AZURE_SUBSCRIPTION }}" -var region="${{ secrets.REGION }}"

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan -var appId="${{ secrets.TF_SPN_ID }}" -var objectId="${{ secrets.TF_SPN_OBJECT }}" -var secret="${{ secrets.TF_SPN_SECRET }}" -var tenant="${{ secrets.AZURE_TENANT }}" -var subscription="${{ secrets.AZURE_SUBSCRIPTION }}" -var region="${{ secrets.REGION }}"
        continue-on-error: true

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}