name: Manage aks-acr infrastructure

on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          #creds: '{"clientId":"${{ secrets.TF_SPN_ID }}","clientSecret":"${{ secrets.secrets.TF_SPN_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION }}","tenantId":"${{ secrets.AZURE_TENANT }}"}'
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Terraform fmt'
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
          
      - name: 'Terraform init'
        id: init
        env:
          ARM_CLIENT_ID:"${{ secrets.TF_SPN_ID }}"
          ARM_CLIENT_SECRET:"${{ secrets.secrets.TF_SPN_SECRET }}"
          ARM_SUBSCRIPTION_ID:"${{ secrets.AZURE_SUBSCRIPTION }}"
          ARM_TENANT_ID:"${{ secrets.AZURE_TENANT }}"
        run: terraform init

      - name: 'Terraform validate'
        id: validate
        run: terraform validate -no-color

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
        continue-on-error: true

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}