name: Manage aks-acr infrastructure

on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_hostname: 'terraform.example.com'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
          
      - name: Terraform Init
        id: init
        run: terraform init -var'appId=${{ secrets.TF_SPN_ID }}' -var'objectId=${{ secrets.TF_SPN_OBJECT }}' -var'secret=${{ secrets.secret }}' -var'tenant=${{ secrets.tenant }}' -var'subscription=${{ secrets.subscription }}' -var'secret=${{ secrets.secret }}' -var'tenant=${{ secrets.tenant }}' -var'region=${{ secrets.region }}'

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - id: plan
        run: terraform plan -no-color -var'appId=${{ secrets.TF_SPN_ID }}' -var'objectId=${{ secrets.TF_SPN_OBJECT }}' -var'secret=${{ secrets.secret }}' -var'tenant=${{ secrets.tenant }}' -var'subscription=${{ secrets.subscription }}' -var'secret=${{ secrets.secret }}' -var'tenant=${{ secrets.tenant }}' -var'region=${{ secrets.region }}'
        continue-on-error: true

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}